completed react-form-controls - YoonHwan Cho
YoonHCho/c0622-code-solutions pull request #120
Opened 2022-09-01 19:48 UTC by YoonHCho

completed react-form-controls - YoonHwan Cho

![react-form-controls](https://user-images.githubusercontent.com/106636383/187999703-33195645-59eb-4783-8453-fd3125e20dc4.gif)

2022-09-01 22:41 UTC, thebearingedge requested changes

2022-09-01 22:41 UTC, thebearingedge commented on react-form-controls/src/index.jsx
> +          <button type="submit" onClick={ this.handleSubmit }>Sign Up</button>
You should listen for `onSubmit` of the form element instead of `onClick` of the button.

2022-09-02 00:15 UTC, YoonHCho commented
Hi Tim,
updated the according to the change request. `onSubmit `on the `form` element and removed `onClick` from `button` element

![image](https://user-images.githubusercontent.com/106636383/188033052-07df71ef-f0cf-448a-99c6-5d40983cf9f3.png)

2022-09-02 00:28 UTC, thebearingedge approved these changes

2022-09-02 00:43 UTC, merged