String manipulation 2 - YoonHwan Cho
YoonHCho/c0622-code-solutions pull request #43
Opened 2022-07-11 23:49 UTC by YoonHCho

String manipulation 2 - YoonHwan Cho
![2022-07-11 16_47_13-String Manipulation 2](https://user-images.githubusercontent.com/106636383/178377273-13733f27-9bb0-426e-b044-96299f3ffdf3.png)

2022-07-13 16:49 UTC, codingcodymiller requested changes

2022-07-13 16:49 UTC, codingcodymiller commented on string-manipulation-2/src/capitalize-word.js
> +    return word;
For extremely special cases like this, you can just hardcode the return value, so `return "JavaScript"`

2022-07-13 17:05 UTC, YoonHCho commented
fixed hardcode return 'JavaScript'

![image](https://user-images.githubusercontent.com/106636383/178790560-97a72b42-07cb-4893-9ba8-9028648a68b0.png)

2022-07-14 18:51 UTC, codingcodymiller approved these changes

2022-07-14 19:36 UTC, merged