Completed javascript-forms - YoonHwan Cho
YoonHCho/c0622-code-solutions pull request #49
Opened 2022-07-13 21:33 UTC by YoonHCho

Completed javascript-forms - YoonHwan Cho
![form-events](https://user-images.githubusercontent.com/106636383/178840489-a0a33789-2606-4c48-a02a-dadd8583dc10.gif)
![form-values](https://user-images.githubusercontent.com/106636383/178840504-6e4152d5-19e6-4a0a-8c2f-3b3174c126dd.gif)

2022-07-13 22:38 UTC, codingcodymiller requested changes

2022-07-13 22:38 UTC, codingcodymiller commented on javascript-forms/form-values.js
> +var object = {};
You should make this inside the function, it doesn't need to continue to exist after the function ends.

2022-07-14 00:23 UTC, YoonHCho commented
thanks cody, replace it inside the function
![image](https://user-images.githubusercontent.com/106636383/178858958-34f91039-ac05-486e-994e-36ed519e7053.png)

2022-07-14 18:34 UTC, codingcodymiller approved these changes

2022-07-14 19:36 UTC, merged